spring.application.name=aggregator

com.fish.aggregator.postgresconfig.url=jdbc:postgresql://localhost:5432/fish_db
com.fish.aggregator.postgresconfig.username=dev
com.fish.aggregator.postgresconfig.password=1111

logging.level.org.springframework.web=DEBUG
logging.level.org.apache.tomcat=DEBUG
logging.level.org.hibernate=DEBUG