CREATE TABLE
  IF NOT EXISTS account (account_id UUID NOT NULL, username TEXT NOT NULL);

/* INSERT INTO
account
VALUES
('2d118350-568c-416d-a9ea-1917af8367ac', 'stevo');

INSERT INTO
account
VALUES
('e9ddb6a9-ae08-460f-8162-ce1e01f39718', 'mike');

INSERT INTO
account
VALUES
('e52fb38e-e241-4a7a-8c69-e531dcf30bd2', 'vince');
 */
CREATE TABLE
  IF NOT EXISTS comment (
    commentid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment TEXT NOT NULL,
    ownerid UUID REFERENCES account (account_id) ON DELETE CASCADE
  );

INSERT INTO
  comment (comment, ownerid)
VALUES
  (
    'This is the first comment',
    '2d118350-568c-416d-a9ea-1917af8367ac'
  );

-- INSERT INTO
--   comment (comment, ownerid)
-- VALUES
--   (
--     'This is the second comment',
--     'e9ddb6a9-ae08-460f-8162-ce1e01f39718'
--   );
-- INSERT INTO
--   comment (comment, ownerid)
-- VALUES
--   (
--     'This is the third comment',
--     'e52fb38e-e241-4a7a-8c69-e531dcf30bd2'
--   );