CREATE TABLE
  IF NOT EXISTS account (
    accountid UUID NOT NULL PRIMARY KEY,
    username TEXT NOT NULL
  );

CREATE TABLE
  IF NOT EXISTS domain (
    domainid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL UNIQUE
  );

CREATE TABLE
  IF NOT EXISTS post (
    postid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    path TEXT NOT NULL,
    accountid UUID NOT NULL,
    domainid BIGINT NOT NULL,
    FOREIGN KEY (accountid) REFERENCES account (accountid),
    FOREIGN KEY (domainid) REFERENCES domain (domainid),
    UNIQUE (domainid, path)
  );

CREATE TABLE
  IF NOT EXISTS upvote (
    upvoteid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid UUID NOT NULL,
    postid BIGINT NOT NULL,
    FOREIGN KEY (accountid) REFERENCES account (accountid),
    FOREIGN KEY (postid) REFERENCES post (postid)
  );

CREATE TABLE
  IF NOT EXISTS comment (
    commentid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment TEXT NOT NULL,
    postid BIGINT REFERENCES post (postid) ON DELETE CASCADE,
    ownerid UUID REFERENCES account (accountid) ON DELETE CASCADE
  );